version: "3.3"

services:

  frontend:
    image: webrtc-frontend
    restart: always
    expose:
      - "443:443"
    volumes:
      - ./frontend:/app

  backend:
    image: webrtc-backend
    restart: always
    expose:
      - "3000:3000"
    volumes:
      - ./backend:/app
