version: "3.3"

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ~/certs:/etc/nginx/certs:ro
      - ~/vhost:/etc/nginx/vhost.d
      - ./frontend/dist/spa:/usr/share/nginx/html

  frontend:
    image: nginx
    restart: always
    expose:
      - "80"
    volumes:
      - ./frontend/dist/spa:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=filefront.invernaderolabs.com
      - LETSENCRYPT_HOST=filefront.invernaderolabs.com
      - LETSENCRYPT_EMAIL=ylazo@invernaderolabs.com
    depends_on:
      - nginx-proxy
      - letsencrypt

  backend:
    image: webrtc-backend
    restart: always
    ports:
      - "3000"
    volumes:
      - ./backend:/app
